# Generated by Django 4.2.16 on 2024-10-02 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя чата')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение чата')),
                ('is_group', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='ChatUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('invite_reason', models.CharField(max_length=255)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
            ],
            options={
                'verbose_name': 'Пользователь чата',
                'verbose_name_plural': 'Пользователи чата',
                'db_table': 'chats_users',
            },
        ),
    ]
