# Generated by Django 4.2.16 on 2024-10-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatusers_last_seen_alter_message_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='time',
        ),
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
